### ISSUE TITLE
Methodology for Analysis of data points in the WG's Survey of existing FAIR assessment tools and approaches

### ISSUE THREAD

**Issue by nkmeyers** [RDA-FAIR/FAIR-data-maturity-model-WG#1]
Hi @RDA-FAIR, 
I have some "catching up with this WG" questions: 
Can you clarify:  have the methodology and/or the resources/datapoints considered for the Analysis of the  [landscape] Survey of existing FAIR assessment tools and approaches been shared anyplace [yet?]  

Maybe this was clear to any WG initiators/participants pre Jan 24 2019 but not so clear for those of us encountering the working group in Feb 2019 and approaching the survey results "cold" here in the github ?  

**Maybe this blurb in the [WG's github "how to contribute:"](https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG#how-to-contribute)is the [landscape] survey methodology statement?**  "_Questions and options stemming from theses different approaches were classified according to the FAIR principles/facets_."  . . .  This resulted in five slide decks that can be found in the folder /results of preliminary analysis

I think we see: 
1)[The survey](https://docs.google.com/spreadsheets/d/14ojMSXVOITg3RoJn-PuDaPj8zuIGQz2Li-kl97HOBH4/edit?usp=sharing) 
2)The [Results](https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/tree/master/results%20of%20preliminary%20analysis)
4)Where is the Methodology?
3)Where are the Data/Resources upon which Results [as presented in the slides] were "generated"? Not Just the [stuff in the sheet, right?](https://docs.google.com/spreadsheets/d/14ojMSXVOITg3RoJn-PuDaPj8zuIGQz2Li-kl97HOBH4/edit?usp=sharing) is there a separate record someplace where the data percolating up on the results as seen on the slides is kept? 

Thanks for the clarification, trying to "catch up"! 
Natalie

**Comment by RDA-FAIR** [comment]
Thank you for your question and we hope everybody will benefit from this clarification. 

Yes, they have been shared; 

1) Last week, the 21st & 22nd of February, we introduced a methodology to the WG during the first online workshop. The slides presented are available on the [RDA WG web page](https://www.rd-alliance.org/workshop-1). The methodology is touched upon at slide seven. 
2) Based on the Google Survey and the publicly available documentation, we did a landscaping exercise to serve as a starting point for the WG. It consisted of clustering questions and options from the different (FAIR) self-assessment tools. The [results](https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/tree/master/results%20of%20preliminary%20analysis/v0.01) are shown in five slide decks. 

In answer to your last question, you can see the resources used in either slide fifty-one of the [slide deck presented last week](https://www.rd-alliance.org/workshop-1) or at the beginning of each one of [the five slide decks](https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/tree/master/results%20of%20preliminary%20analysis/v0.01). But there is no separate record per se, we will consider making one. 

We hope that we answered your questions. 
If something remains unclear do not hesitate to contact us. 

The editor team
