### ISSUE TITLE
Findable: What does it mean?

### ISSUE THREAD

**Issue by gepeng86** [RDA-FAIR/FAIR-data-maturity-model-WG#10]
What does it mean to be findable? Using a data set/file as an example, this slide explores different scenarios/stages that a dataset or file can be found by both human and machines. Dataset metadata record does not necessarily exist for the first two stages. It also touches on a number of potential implementation challenges for assessing if a dataset is findable, especially if using just machines without human intervention. 

This slide is intended to demonstrate the fact that there is a wide range of scenarios under the statement of “Data is findable”.
[GePeng_WhatDoesItMean_ToBeFindable_v01r00_20190324.pdf](https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/files/3005258/GePeng_WhatDoesItMean_ToBeFindable_v01r00_20190324.pdf)
.

**Comment by rwwh** [comment]
Different research fields have different challenges, there can not be a single assessment that for every data file decides whether it is findable or not. The FAIR principles (and their assemblage in your PDF) can give guidance where you could look if you need to make the data more FAIR. Important two steps that I recognize is (a) being able to find again what you already know (b) being able to locate something relevant that you did not know yet (cf also [Search vs Discovery](https://seths.blog/2014/04/search-vs-discovery/) ).

At a meeting on Data Management organised at CERN in 2016, an interdisciplinary group discussed about findability and what level is necessary. I paraphrase the two extremes as:

1. High-energy physics. This field is dominated by a few very famous experiments. The name of a data set is probably enough to find it. Simple example: a researcher interested in electron-positron collisions can name all the instruments in the world that have done experiments on these, and therefore findability is good enough if he can locate the data sets based on the name of the instrument. 
2. Life Sciences. There are not thousands but probably a million life science researchers in the world. And their (reusable) datasets are often collected in relatively small experiments. This results in thousands of databases that all could be valuable. Findability in this field means that a researcher can locate data sets that happen to have some suitable characteristics. Simple example: a researcher may be looking for any data set in which the body mass of a human is stored together with whether he is suffering from diabetes or not. This may include many data sets that were not made by diabetes researchers. And also note that this search should locate restricted access data sets that contain sensitive personal data.
