### ISSUE TITLE
Beyond the aspects of data and the FAIR principles - 'X' strand

### ISSUE THREAD

**Issue by RDA-FAIR** [RDA-FAIR/FAIR-data-maturity-model-WG#11]
1. Data flow, which is clear and recognized, but not necessarily solved.
2. Hardware infrastructure: while there is work around repositories, the networks are not considered. Yet, they play a major role in the **accessibility**. 
3. People (e.g. researchers, professors, students) is not something to be forgotten. Basic Trust and identities are solved, but if there is a hierarchy and different levels of authorization, it can be an issue. 
4. Data flow related legal issues: security, safety, copyright, etc. It will be territorial as the legislation itself is territorial, but again hybrid data will be an issue. 
5. Financial flow: up to the business model and likely territorial, but in reality connected to the FAIR assessment in many ways.

**Comment by JPetters2931** [comment]
Do we want to assess the level of openness of their data (something that the FAIR principles do not cover)?

**Comment by keithjeffery** [comment]
There is a need to define criteria and metrics (may be close to those for data) for software services, opensource software modules, sensors - sensor networks,  lab equipment, computing resources......
