### ISSUE TITLE
At what level is data and associated information considered to be FAIR-Accessible?

### ISSUE THREAD

**Issue by gepeng86** [RDA-FAIR/FAIR-data-maturity-model-WG#12]
What does it mean to be accessible? Using a data set/file as an example, this slide explores different scenarios/stages that a dataset and associated information can be accessible by both human and machines.

This slide is intended to demonstrate the fact that there is a wide range of scenarios under the statement of “Data is accessible” in order to help reach a consensus on how to define and assess FAIR-Accessible.
[GePeng_WhatDoesItMean_ToBeAccessible_v01r00_20190329.pdf](https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/files/3023029/GePeng_WhatDoesItMean_ToBeAccessible_v01r00_20190329.pdf)

Labels: Accessibility; FAIRness; Scope

**Comment by rwwh** [comment]
Here again the desired level of accessibility is dependent on the situation (e.g. discipline). One should continuously weigh what could be done and at which cost, against the benefits for re-use of the data.

Over time, such considerations will result in access procedures to restricted data sets requiring the least number of steps of human intervention; will reduce the number of different ways persistent identifiers need to be queried and resolved; will standardize the way a repository gives access to data and metadata; will reduce the burden of multiple authentication and authorization systems.
