### ISSUE TITLE
Indicators for F1: (meta)data are assigned a globally unique and eternally persistent identifier

### ISSUE THREAD

**Issue by makxdekkers** [RDA-FAIR/FAIR-data-maturity-model-WG#15]
![image](https://user-images.githubusercontent.com/7534601/60016361-493c8d80-9686-11e9-8ad0-de0c2c1b44a6.png)

**Comment by makxdekkers** [comment]
Points raised in online meeting #3 on 18 June 2019

- What could be the definition of ‘Unique’ and ‘Persistent’?
- The main requirement for identifiers are that they are persistent and unambiguous.
- It was proposed to change ‘Global’ to ‘Universal’.
- Resolvability of the persistent identifier should be part of A1 rather than F1 as resolution of identifiers is not about Findability. 
- ‘Resolve’ should be renamed ‘Resolvability’.
- Sometimes some identifiers do not resolve, and if they do ‘what they resolve to’ may not be the same in all cases; for example, sometimes an identifier points to a digital proxy, such as landing page. 
- The indicators need to be duplicated, as both the data and the metadata are in scope for the principle.
- The ultimate goal is to identify an object in a given state.

**Comment by RDA-FAIR** [comment]
![image](https://user-images.githubusercontent.com/47179213/60704015-8fee7b00-9f03-11e9-945e-6da353f34f96.png)

**Comment by RDA-FAIR** [comment]
Please find the current version of the indicator(s) and their respective maturity levels for this FAIR principle. Indicators and maturity levels will be presented, as they stand, to the next working group meeting for approval.  In the meantime, any comments are still welcomed.

The editorial team will now concentrate on weighing and prioritizing these indicators. More information soon.

![image](https://user-images.githubusercontent.com/47179213/62354008-2cf50180-b50c-11e9-9c1f-da6b748b4092.png)

**Comment by kitchenprinzessin3880** [comment]
1. What is the difference between 'universally unique and 'unambiguous identifier'? Suggestion : change the answer option to 'Universally unique identifier'. Keep it short and simple ;)
2. I am not sure if Resolvability of the persistent identifier should be part of A1 as persistence means the identifier **reliably points to a digital resource over the Web**. So with regards to F1-01M,F1-01D, what are their means of verification?

**Comment by makxdekkers** [comment]
@kitchenprinzessin3880 
1. In the overview of the indicators with their proposed priorities, to be presented in the meeting on 12 September, we have suppressed the answer options. We will take you comment into account when we update the detailed definitions of the indicators
2. The resolvability could indeed also be here at F1, but it was proposed for A1. We do not currently consider the means of verification of the indicators; we are looking at **what** is to be evaluated, not **how** the indicators could be evaluated. However, it has already been suggested that the evaluation could rely on registries like https://fairsharing.org/.

**Comment by bahimc** [comment]
Dear contributors,
 
Below you can find the indicators and their maturity levels in their current state as a result of the above discussions and workshops.
 
![image](https://user-images.githubusercontent.com/47179213/66298412-f06dc980-e8f1-11e9-937a-0727c78ac635.png)
 
**Please note that this thread is going to be closed**, within a short period of time.  The current state of the indicators, as of early October 2019, is now frozen, with the exception of the indicators for the principles that are concerned with ‘richness’ of metadata (F2 and R1). The current indicators will be used for the further steps of this WG, which are prioritisation and scoring.  Later on, they will be used in a testing phase where owners of evaluation approaches are going to be invited to compare their approaches (questionnaires, tools) against the indicators. The editorial team, in consultation with the Working Group, will define the best approach to test the indicators and evaluate their soundness. As such, the current set of indicators can be seen as an ‘alpha version’. In the first half of 2020, the indicators may be revised and improved, based on the results of the testing. **If you have any further comments, suggestions regarding that specific discussion, please share them with us. Besides, we invite you to have a look at the following two sets of issues.**
 
**Prioritisation**
 
[• Indicators prioritisation for Findability
](https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/30)[• Indicators prioritisation for Accessibility](https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/31)
[• Indicators prioritisation for Interoperability
](https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/32)[• Indicators prioritisation for Reusability ](https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/33)
 
**Scoring** 
 
[• Indicators for FAIRness | Scoring
](https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/34) 
We thank you for your valuable input!
