### ISSUE TITLE
Indicators for F2: data are described with rich metadata 

### ISSUE THREAD

**Issue by makxdekkers** [RDA-FAIR/FAIR-data-maturity-model-WG#16]
![image](https://user-images.githubusercontent.com/7534601/60016552-d7187880-9686-11e9-9e12-14ff5c7263c9.png)

**Comment by makxdekkers** [comment]
Points raised in online meeting #3 on 18 June 2019

- The landing page is targeted to human users, and cannot be interpreted automatically as there is no guarantee that it contains structured data. It also introduces an extra step between the identifier and the asset. However, DOIs point often to a landing page. 
- F2 is about the richness of metadata for discoverability. Rich metadata for reuse are covered under the principles for the area Reusable.
- The contextualisation is an important part of F2.
- ‘Rich’ metadata is a property of degree rather than being a binary YES/NO. There is a possibility that a digital object satisfies all the indicators proposed yet the metadata could not be qualified as ‘Rich’.
- Additional indicators for ‘Rich’ metadata may have to be defined by the context and the domain. However, a set of core indicators for ‘Rich’ metadata should be universal and cross-domain.

**Comment by makxdekkers** [comment]
See also #13

**Comment by RDA-FAIR** [comment]
Please find the current version of the indicator(s) and their respective maturity levels for this FAIR principle. Indicators and maturity levels will be presented, as they stand, to the next working group meeting for approval.  In the meantime, any comments are still welcomed.

The editorial team will now concentrate on weighing and prioritizing these indicators. More information soon.

![image](https://user-images.githubusercontent.com/47179213/62354080-5c0b7300-b50c-11e9-92d7-e39dffca9ef5.png)

**Comment by SusannaSansone** [comment]
@makxdekkers as in #26 what is the metadata defined by the RDA metadata IG? If you are to point people to some metadata lists, then you should consider also point them to the RDA FAIRsharing WG registry for generic and domain/disciplines standards, since it is an approved/adopted RDA output.

**Comment by makxdekkers** [comment]
@SusannaSansone The Metadata IG lists a set of metadata elements on their RDA page at https://www.rd-alliance.org/groups/metadata-ig.html (scroll down a bit). This was proposed by a member of the WG, and this proposal is open for discussion by the WG. As I proposed in https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/13#issuecomment-518015822, we can refer to FAIRsharing in the indicator F2-01M. Is that OK?

**Comment by kitchenprinzessin3880** [comment]
a set of core indicators for ‘Rich’ metadata should be universal and cross-domain.
+1
'sufficient metadata to allow discovery is provided'-> we may consider metadata elements required for citing datasets as the sufficient (minimum) metadata. They are domain independent.

**Comment by makxdekkers** [comment]
@kitchenprinzessin3880 Is there a standard for 'the elements required for citing datasets'?

**Comment by kitchenprinzessin3880** [comment]
@makxdekkers not really standard but recommendations, see below:
1. page 11 at https://schema.datacite.org/meta/kernel-4.1/doc/DataCite-MetadataKernel_v4.1.pdf
2. https://www.force11.org/node/4771
Both formats have similar citation properties.

**Comment by makxdekkers** [comment]
@kitchenprinzessin3880 It seems to me that your proposal is for a minimum set of metadata, which is not really the same as 'rich metadata'. Not sure how to capture this in the indicators for F2 and R1. How would you suggest doing that?

**Comment by kitchenprinzessin3880** [comment]
@makxdekkers 
My suggestion is to specify three indicators of F2
F2-01M (new) ->Minimum metadata are provided, e.g. for citing datasets....
F2-02M -> Sufficient metadata is provided to allow discovery......
F2-03M -> Metadata is provided for the discovery related element......

F2-01M (new) is domain independent and by practice published datasets should have this information. 

A slightly related question: i just joined the group recently, so i missed earlier discussions on the indicator. Where can I find examples/means of verification of the indicators?

**Comment by makxdekkers** [comment]
@kitchenprinzessin3880 My question would be if you would consider data FAIR if there was only minimum metadata? As you define it, it would be less metadata than sufficient for discovery -- is this not in contradiction with the principle?

On your question about the examples/means of verification, the scope of the Working Group at this moment is to develop the methodology for 'what' is to be evaluated, not 'how' the indicators will be evaluated.

**Comment by kitchenprinzessin3880** [comment]
@makxdekkers 
> the scope of the Working Group at this moment is to develop the methodology for 'what' is to be evaluated, not 'how' the indicators will be evaluated.
noted.

> My question would be if you would consider data FAIR if there was only minimum metadata? 
As you define it, it would be less metadata than sufficient for discovery -- is this not in contradiction with the principle?
i agree that the more metadata (with good quality) the better the data discovery. my suggestion before primarily focuses on metadata comes in with different granularity levels, starting from minimum metadata elements to find a dataset, followed by minimum+additional elements to advance discovery.

**Comment by rwwh** [comment]
In my experience for F2 there is a very important aspect of metadata _quality_ in addition to _quantity_: it is essential that the metadata expresses **what the data is**, and **not how it was originally intended to be used**. For example, if you are looking for a way to showcase your rock collection, you may be more likely to look for a **set of shelves** (what it is) than for a **book cupboard** (how these shelves may have initially been intended). Classifications of e.g. patents are based on this kind of premise.

See also [a blog post I made about this a while ago](http://www.hooft.net/en/people/rob/events/193-tell-me-what-it-is-not-how-you-use-it)

**Comment by SusannaSansone** [comment]
> @SusannaSansone The Metadata IG lists a set of metadata elements on their RDA page at https://www.rd-alliance.org/groups/metadata-ig.html (scroll down a bit). This was proposed by a member of the WG, and this proposal is open for discussion by the WG. As I proposed in [#13 (comment)](https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/13#issuecomment-518015822), we can refer to FAIRsharing in the indicator F2-01M. Is that OK?

@makxdekkers sure, I have suggested referring to FAIRsharing in few points, as a place (because this is not a standards to be clear) where people can discover the wealth of community-defined metadata standards (generic and domain/discipline specific).

**Comment by makxdekkers** [comment]
Peter Wittenburg at https://docs.google.com/spreadsheets/d/1mkjElFrTBPBH0QViODexNur0xNGhJqau0zkL4w8RRAw/edit?disco=AAAADadg7hI

On F2-01M:
FAIR principles say "rich" metadata which allows interpretations. Here you only speak about metadata for discovery which can only be a first step. For using metadata in building collections for further scientific processing, discovery metadata is not sufficient. Also when we look a few years ahead and implement necessary steps towards automation discovery metadata will not be sufficient. This needs to be reflected somehow in the indicators.

**Comment by makxdekkers** [comment]
Peter Wittenburg at https://docs.google.com/spreadsheets/d/1mkjElFrTBPBH0QViODexNur0xNGhJqau0zkL4w8RRAw/edit?disco=AAAADadg7hM


On F2-02M:
I think that this formulation is excellent. It gives the RDA MD group a clear task as a neutral place to bring interests together.

**Comment by makxdekkers** [comment]
Peter, on your comment https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/16#issuecomment-522305712 about F2-01M, you are right: "rich metadata" should include more than discovery metadata. However, this indicator is for F2 which is under Findable, so therefore we thought it made sense to focus here on the discovery aspect in the indicator. The reuse aspect is covered in indicator R1-01M (see https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/26#issuecomment-517604325).

**Comment by makxdekkers** [comment]
The richness required for FAIR Data will be discussed at a joint meeting of the Metadata Standards Catalog WG, Metadata IG, Data in Context IG, FAIRSharing Registry: connecting data policies, standards & databases WG, FAIR Data Maturity Model WG and the ESIP/AGU/RDA Enabling FAIR Data Coordination Group at the 14th RDA plenary: https://www.rd-alliance.org/metadata-fair-data.
