### ISSUE TITLE
Indicators for F3: metadata clearly and explicitly include the identifier of the data it describes

### ISSUE THREAD

**Issue by makxdekkers** [RDA-FAIR/FAIR-data-maturity-model-WG#17]
![image](https://user-images.githubusercontent.com/7534601/60016719-40988700-9687-11e9-98f2-789563a6beee.png)

**Comment by makxdekkers** [comment]
Points raised in online meeting 3 on 18 June 2019

- The structure of identifiers may also be considered.

**Comment by RDA-FAIR** [comment]
![image](https://user-images.githubusercontent.com/47179213/60704142-e360c900-9f03-11e9-9df1-a10b2aa9f062.png)

Here is a new version of the indicator!

**Comment by RDA-FAIR** [comment]
Please find the current version of the indicator(s) and their respective maturity levels for this FAIR principle. Indicators and maturity levels will be presented, as they stand, to the next working group meeting for approval.  In the meantime, any comments are still welcomed.

The editorial team will now concentrate on weighing and prioritizing these indicators. More information soon.

![image](https://user-images.githubusercontent.com/47179213/62354331-db994200-b50c-11e9-9be3-c5707862df75.png)

**Comment by kitchenprinzessin3880** [comment]
+1 (the answer options are short and direct).

**Comment by rwwh** [comment]
I'm wondering a bit how things work together if it is this simple. A PID for a dataset usually resolves to a URL that contains metadata of the dataset, including, if possible, a link to the actual data.  Adding the PID back into that metadada may be useful but is not ground breaking.

The metadata including the identifier of the data that it describes becomes really important when

- there is additional metadata elsewhere. 
- it is impossible to add a link to the metadata in the object itself

But these are hard to capture in the maturity indicators, because how is such metadata located if it does not contain the PID? One idea of F3 is that it would be possible in a FAIR ecosystem to locate any metadata by using the persistent identifier of the data as a search term.

**Comment by keithjeffery** [comment]
1. a UUPID in metadata in a property or attribute 'field' should point to the data, not other metadata (the DataCite/DoI problem);
2. however, it is more complex than this.  There may not be a simple (hierarchic) relationshp between metadata and data (or services, software module, workflow, computing resource, person, organisation......).  To represent the real world a fully connected graph of relaitonships is required.  For example, two different metadata 'records' may point to (describe0 the same data (or other digital asset).
3. for metricating the FAIR principle it seems to me there is a binary (Y/N) decision on whether the metadata includes a UUPID for the data in an appropriately labelled property/attribute/field.

**Comment by RDA-FAIR** [comment]
On the 19/08/2019 Mark D Wilkison commented

There are cases where the PID of the data resolves to the metadata. How could that situation be captured in the indicators?

> the question is internally inconsistent.  FAIR requires that the data and the metadata have distinct identifiers (because they are not the same thing!), so...   (For those who remember history, there was a protocol in the past, the LSID, that solved this problem by having a single identifier for the data and the metadata, and then providing them independently via two distinct Web calls - getData, getMetadata.  With HTTP, we are stuck with GET, so we must have distinct identifiers for the two kinds of information.) (that is not to preclude that other identifier systems - beyond URIs - might exist now or in the future, and should be evaluated by the same rules)

Read his comment here: https://www.rd-alliance.org/group/fair-data-maturity-model-wg/post/discussion-items-fair-data-maturity-model-19-august-2019

**Comment by makxdekkers** [comment]
@keithjeffery Your point 3 is the intention of indicator F3-01M. Is anything more needed?

**Comment by makxdekkers** [comment]
The issue of the identification is raised for discussion at the online meeting on 12 September 2019, slide 26 in the presentation at https://www.rd-alliance.org/workshop-4.
