### ISSUE TITLE
Indicators for F4: (meta)data are registered or indexed in a searchable resource

### ISSUE THREAD

**Issue by makxdekkers** [RDA-FAIR/FAIR-data-maturity-model-WG#18]
![image](https://user-images.githubusercontent.com/7534601/60016815-848b8c00-9687-11e9-8f3c-a2744a2bc900.png)

**Comment by makxdekkers** [comment]
Points raised in online meeting 3 on 18 June 2019

- Clarifications are needed for the portals (e.g. domain specific aggregator?) and for the repositories. 
- Not all the proposed indicators are needed. 
- Possibility to include some notions of what constitutes a trusted (or managed) repository.
- Something could be indexed, but it doesn’t mean that someone can do anything with the information that is associated with the index entry.
- The aspect of universal accessibility of the search system needs to be considered.

**Comment by RDA-FAIR** [comment]
Please find the current version of the indicator(s) and their respective maturity levels for this FAIR principle. Indicators and maturity levels will be presented, as they stand, to the next working group meeting for approval.  In the meantime, any comments are still welcomed.

The editorial team will now concentrate on weighing and prioritizing these indicators. More information soon.

![image](https://user-images.githubusercontent.com/47179213/62354359-eb188b00-b50c-11e9-89ec-7942185d16bb.png)

**Comment by SusannaSansone** [comment]
@makxdekkers is "metadata is harvested by or submitted to a generalist repository" missing, or have I misunderstood this?

**Comment by makxdekkers** [comment]
@SusannaSansone There has been no mention so far in the WG of a "generalist repository". We can of course add an indicator for that. Would you have an example of such a repository?

**Comment by kitchenprinzessin3880** [comment]
Suggestion: 
1. remove 'general' -> Metadata or landing page is harvested by **a** search engine
2. remove 'landing page' from 'Metadata or landing page'..
2. since this metric related to Findability why don't we use findable instead of harvest? e.g., Metadata is findable through a search engine..

**Comment by makxdekkers** [comment]
@kitchenprinzessin3880 We refer to 'general' search engines to distinguish them with the domain/discipline-specific ones.
The landing page is mentioned here because there are some dataset publishers that create landing pages with structured metadata, e.g. using schema.org to get them harvested by the major search engines.
The indicator refers to harvested by/submitted to make it active -- findable is the result of such actions.
But we can of course change the wording if the working group agrees.

**Comment by SusannaSansone** [comment]
> @SusannaSansone There has been no mention so far in the WG of a "generalist repository". We can of course add an indicator for that. Would you have an example of such a repository?

@makxdekkers i was thinking Drayd, or Figshare or Github; or have i misunderstood your point?

**Comment by makxdekkers** [comment]
Peter Wittenburg at https://docs.google.com/spreadsheets/d/1mkjElFrTBPBH0QViODexNur0xNGhJqau0zkL4w8RRAw/edit?disco=AAAADadg7rg

On F4-01M:
I don't understand this formulation. What does "landing page" mean? Why not just say that metadata must be offered in a way that it ccan be harvested by a search engine. As data provider you cannot force anyone to harvest your metadata - you can only offer it in standard ways. Then the question is what are these standard ways. We offered metadata for example via OAI/PMH, as HTML for Google etc and as RDF for triple store integration etc.

**Comment by makxdekkers** [comment]
Peter Wittenburg at https://docs.google.com/spreadsheets/d/1mkjElFrTBPBH0QViODexNur0xNGhJqau0zkL4w8RRAw/edit?disco=AAAADadg7rk

On F4-02M:
Here the same comment is true: you can only offer it (or in case of push model) submit it. The format is then defined by the intention and the harvester.

**Comment by makxdekkers** [comment]
Peter, are you suggesting that we reformulate the indicators to say "metadata is offered in such a way that it can be harvested and indexed ..."?

**Comment by keithjeffery** [comment]
How did the concept of landing page creep into this discussion?  I don't think landing pages are relevant - it is a mechanism that obstructs autonomic processing hence practical interoperability/re-use. 
The FAIR criterion is metadata registered or indexed in a searchable resource.  The searchable resource could be a repository of metadata records (or that part of a repository of digital objects which is metadata records), a catalog - even a well-marked up web page (probably XML rather than HTML).  Registered in indicates a UUPID. Indexed indicates sufficient metadata properties/attributes/fields for the intended purpose.  Searching should be on UUPID or some combination of values of metadata properties/attributes/fields.

**Comment by RDA-FAIR** [comment]
On the 19/08/2019 Mark D Wilkinson commented

The formulation “_metadata is harvested by_” does not put the responsibility on the data provider; a provider cannot force anyone to harvest the metadata. It might be better to change this to “_metadata is offered/made available in such a way that it can be harvested and indexed by …_”

> This is an extremely hard Principle to adhere-to, at the moment.  Most search engines do not harvest structured metadata at all; some harvest only certain types of metadata (e.g. schema.org); search engines don't have a common search interface, meaning we have to code to each one; and many search engines that DO harvest metadata, are not allowed to be accessed automatically (e.g. Google dataset search).  So... I think the best thing is to simply talk about the problems here, and suggest that we all find a way to do better.  I cannot think of a "good" solution for this Principle, at the moment...  (my test uses Bing, only because I am allowed to automate search against Bing!  But it doesn't index metadata very well; doesn't index DOIs **at all**!!; and it seems to refuse to index pages that primarily contain structured metadata, like the search interface to one of my databases, that provides a google-like search box as its only HTML element, but provides a 2-page JSON-LD metadata record about what is in the database!  LOL!  Bing wont index that page at all!)
So I would suggest that this is "an ongoing problem, with no good solution to-date"

Read his comment here: https://www.rd-alliance.org/group/fair-data-maturity-model-wg/post/discussion-items-fair-data-maturity-model-19-august-2019

**Comment by makxdekkers** [comment]
@markwilkinson When you say that the **principle** is extremely hard to adhere to, would that mean that it is not a good idea to have **indicators** for it?

On the other hand, if there is no requirement (expressed as an indicator) to publish metadata in such a way that it can be indexed somewhere, how can the data resource be found?

**Comment by makxdekkers** [comment]
@keithjeffery The 'landing page' crept into the discussion because we picked it up from one of the contributions in the collaborative spreadsheet at https://docs.google.com/spreadsheets/d/1gvMfbw46oV1idztsr586aG6-teSn2cPWe_RJZG0U4Hg/edit#gid=11147031.
The idea is, I guess, that a landing page for a data resource can be picked up and indexed by a search engine, which is one way of making the resource findable (on a low, but potentially useful level).
We can to remove the mention of landing pages if you think it is inappropriate.

**Comment by makxdekkers** [comment]
There is a proposal at https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/30#issuecomment-526520337 to collapse the three indicators into a single one:

**Metadata is offered/published/exposed in such a way that it can be harvested and indexed.**

leaving it unspecified how and by whom the harvesting and indexing is done.

**Comment by makxdekkers** [comment]
@SusannaSansone wrote on 28 August at https://docs.google.com/spreadsheets/d/1mkjElFrTBPBH0QViODexNur0xNGhJqau0zkL4w8RRAw/edit#gid=0

Why only a institutional repository? What about the thousands of community-endorsed repositories (https://fairsharing.org/databases)?
14:10 28 Aug

**Comment by makxdekkers** [comment]
@SusannaSansone Community-endorsed repositories could be covered by the domain/discipline-specific portals in F4-02M. But again, maybe we can collapse the three indicators to one?

**Comment by bahimc** [comment]
Dear contributors,
 
Below you can find the indicators and their maturity levels in their current state as a result of the above discussions and workshops.
 
![image](https://user-images.githubusercontent.com/47179213/66298864-ba7d1500-e8f2-11e9-8f8d-e45d5e8847e4.png)
 
**Please note that this thread is going to be closed**, within a short period of time.  The current state of the indicators, as of early October 2019, is now frozen, with the exception of the indicators for the principles that are concerned with ‘richness’ of metadata (F2 and R1). The current indicators will be used for the further steps of this WG, which are prioritisation and scoring.  Later on, they will be used in a testing phase where owners of evaluation approaches are going to be invited to compare their approaches (questionnaires, tools) against the indicators. The editorial team, in consultation with the Working Group, will define the best approach to test the indicators and evaluate their soundness. As such, the current set of indicators can be seen as an ‘alpha version’. In the first half of 2020, the indicators may be revised and improved, based on the results of the testing. **If you have any further comments, suggestions regarding that specific discussion, please share them with us. Besides, we invite you to have a look at the following two sets of issues.**
 
**Prioritisation**
 
[• Indicators prioritisation for Findability
](https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/30)[• Indicators prioritisation for Accessibility](https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/31)
[• Indicators prioritisation for Interoperability
](https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/32)[• Indicators prioritisation for Reusability ](https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/33)
 
**Scoring** 
 
[• Indicators for FAIRness | Scoring
](https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/34) 
We thank you for your valuable input!
