### ISSUE TITLE
What would be the assessed entity?

### ISSUE THREAD

**Issue by RDA-FAIR** [RDA-FAIR/FAIR-data-maturity-model-WG#2]
What would be the **scope** of the self-assessment model for measuring the FAIRness (e.g. metadata, dataset, digital resource, etc.)?

**Comment by JPetters2931** [comment]
Following the Joint Declaration of Data Citation Principle for Access, perhaps the object to assess is the citable object (however large and heterogeneous it is) and information on its associated landing page (i.e. its metadata).

**Comment by RDA-FAIR** [comment]
**This issue has been resolved**. You can find further information about it in the _Presentation_ (slide 10) and _Report_ (page 6) of the second workshop https://www.rd-alliance.org/workshop-2
