### ISSUE TITLE
Indicators for I1: (meta)data use a formal, accessible, shared, and broadly applicable language for knowledge representation	

### ISSUE THREAD

**Issue by makxdekkers** [RDA-FAIR/FAIR-data-maturity-model-WG#23]
![image](https://user-images.githubusercontent.com/7534601/60017339-d1239700-9688-11e9-8f9e-2fb36a9856bc.png)

**Comment by makxdekkers** [comment]
Points raised in online meeting 3 on 18 June 2019

- There is a slight difference between machine-readable and machine-understandable. The latter is needed for autonomous processing. That point could include a subset of indicators for actionability, readability, understandability, interpretability.
- What is an acceptable language for knowledge representation?
- A formal syntax (e.g. XML) should be one of the levels of the ‘format’ indicator.
- Community-standard format and proprietary format might overlap. If the indicator is maintained, there is still a difference for data and metadata. 
- It might be better to distinguish ‘syntax’ versus ‘semantic’.
- ‘Open’ should replace ‘Community-standard’ as opposed to ‘Proprietary’.
- In some disciplines, researchers only use proprietary formats. If the indicator remains, it means that some of the digital objects would never become FAIR. There may be a preference for open formats, but it is simply not always available.

**Comment by makxdekkers** [comment]
See also #14

**Comment by RDA-FAIR** [comment]
Please find the current version of the indicator(s) and their respective maturity levels for this FAIR principle. Indicators and maturity levels will be presented, as they stand, to the next working group meeting for approval.  In the meantime, any comments are still welcomed.

The editorial team will now concentrate on weighing and prioritizing these indicators. More information soon.

![image](https://user-images.githubusercontent.com/47179213/62354570-7eea5700-b50d-11e9-82ed-e12295b2df97.png)

![image](https://user-images.githubusercontent.com/47179213/62354577-81e54780-b50d-11e9-86b3-d795910c23ec.png)

**Comment by SusannaSansone** [comment]
@makxdekkers for example a computer-based mathematical models can be machine readable and understandable and expressed in XML or other metaformat, but it will not be necessary compliant to the CellML https://doi.org/10.25504/FAIRsharing.50n9hc that is a community-defined and used model/format for computer-based mathematical models. How can we make this clearer or is already in your indicators?

**Comment by makxdekkers** [comment]
@SusannaSansone The way I understand this, indicators I2-01M and I2-01D do already refer to community standards. In the example you give, the model would fail on indicators I2-01M andor I2-01D, because it is not compliant with the community standard. Or am I misreading your comment?

**Comment by kitchenprinzessin3880** [comment]
- Does I1-01D refer to machine readability? Are the options are binary or multiple choices. what happens when a data provider supports proprietary and as well as community data standards?

**Comment by makxdekkers** [comment]
@kitchenprinzessin3880 No, I1-01D is not about machine-understandable; that is covered in I2-02D.
As to the proprietary versus community data standards, I think that proprietary formats would not count as FAIR, but maybe the WG thinks otherwise?

**Comment by makxdekkers** [comment]
Apologies, I wrote I2-02D in the previous comment -- now corrected to I1-02D.

**Comment by kitchenprinzessin3880** [comment]
@makxdekkers - i think i am missing some contexts related I1-01D and I1-02D. What is the difference between these indicators?

**Comment by makxdekkers** [comment]
@kitchenprinzessin3880 I1-01D is about the proprietary or standard format (which does not necessarily need to be machine-understandable) while I1-02D focuses on the machine-understandability.

**Comment by SusannaSansone** [comment]
> @SusannaSansone The way I understand this, indicators I2-01M and I2-01D do already refer to community standards. In the example you give, the model would fail on indicators I2-01M andor I2-01D, because it is not compliant with the community standard. Or am I misreading your comment?

@makxdekkers my example of data formatted in CellML https://doi.org/10.25504/FAIRsharing.50n9hc will not fail, but pass the validation because  CellML is 'the' community-defined and used model/format for computer-based mathematical models. If instead I had a formatted my model in XML, it would be made machine readable but it will not comply to community spec (in this case CellML), hence fail (at least from the view of the community that has developed and used CellML). So my point is: saying that data needs to be machine readable is not = to comply to a community spec (if one exists). The latter needs to be encouraged of course.

**Comment by makxdekkers** [comment]
Peter Wittenburg at https://docs.google.com/spreadsheets/d/1mkjElFrTBPBH0QViODexNur0xNGhJqau0zkL4w8RRAw/edit?disco=AAAADadg-So

On I1-01M:
We need to make sure that it does not matter how repositories represent metadata internally. By far most people use fast relational databases which in general is not called "knowledge representation". Relevant is how metadata is presented to the "outside" world and here a proper knowledge representation should be chosen such as for example RDF.

**Comment by makxdekkers** [comment]
Peter Wittenburg at https://docs.google.com/spreadsheets/d/1mkjElFrTBPBH0QViODexNur0xNGhJqau0zkL4w8RRAw/edit?disco=AAAADadg-Ss

On I1-03M:
Don't know what "self-describing" means.

**Comment by makxdekkers** [comment]
Peter Wittenburg at https://docs.google.com/spreadsheets/d/1mkjElFrTBPBH0QViODexNur0xNGhJqau0zkL4w8RRAw/edit?disco=AAAADadg-Uc

On I1-01D:
Big data usually deals with sequences of numbers which are structured defined by a schema. In general we don't use the term "knowledge representation" for this. Knowledge about the structured sequences of numbers is contained in th metadata. Either the term "knowledge representation" needs to be explained that it includes such structured sequences or a different term should be used. It's an old discussion about FAIR.

**Comment by makxdekkers** [comment]
Peter, maybe @SusannaSansone's comment at https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/14#issuecomment-519987483 helps to define what is part of 'knowledge representation'? Would what you refer to in your comment fit under the **models/format** category?

**Comment by keithjeffery** [comment]
I agree with Peter that many catalogs are in RDBMS forma for perfoemance and integrity (reerential integrity, funcitonal integrity).  I also agree that the key is how the knowledge is represented to interoperating software (associted with repositories, applications/services, agents on behalf of users...).  Let us not fall into the trap that knowledge representation can only be in RDF (or one of its syntactic encodings eg Turtle).  Triples can also be encoded as relational tuples (or Prolog assertions or Object-database representations or...); in fact relational n-tuples can provide much richer knowledge represenation in a more compact form than RDF - and interconversion is feasible.

**Comment by RDA-FAIR** [comment]
On the 19/08/19, Mark D Wilkinson commented

Big data does not use the term "knowledge representation" the same way. Knowledge about the structured sequences of numbers is contained in the metadata. The term "knowledge representation" needs to be explained that it includes such structured sequences or a different term should be used.

> Michel and I had a long discussion about this at the biohackathon last year (or maybe the year before?).  "knowledge representation", originally (among our initial FAIR Metrics group) meant that the language had a BNF.  I am personally not happy with that definition (though we have never created a better one, in a formal way).  Lots of formal data structures structures have BNFs, but they are not able to communicate "meaning", only structure (or at best, grammatical "meaning" - e.g. this is a thing, and this is a property).  I think FAIR intended something much deeper than that!  ...but I don't know how to define it.  It must at least be able to represent concepts that are defined elsewhere (i.e. it must be able to refer outwards to defined concepts, e.g. in an ontology)

Read his comment here: https://www.rd-alliance.org/group/fair-data-maturity-model-wg/post/discussion-items-fair-data-maturity-model-19-august-2019

**Comment by makxdekkers** [comment]
@markwilkinson It seems to me that it is hard to define reasonable indicators for I2 if there is no commonly accepted definition for 'knowledge management'!

@SusannaSansone gave a list of things at https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/14#issuecomment-519987483 that might be used as a starting point. Please comment there if you agree or disagree.
