### ISSUE TITLE
Indicators for R1: meta(data) are richly described with a plurality of accurate and relevant attributes

### ISSUE THREAD

**Issue by makxdekkers** [RDA-FAIR/FAIR-data-maturity-model-WG#26]
![image](https://user-images.githubusercontent.com/7534601/60017634-82c2c800-9689-11e9-950a-217209e0db37.png)

**Comment by makxdekkers** [comment]
Points raised in online meeting 3 on 18 June 2019

- The RDA Metadata IG working on relevant attributes to include in metadata. This WG could liaise with them and further build the indicators related to metadata on their work.
- ‘Richly described with a plurality of accurate and relevant attributes’ is relative - so how can it be tested?
- Richness needs to be defined by the community taking into account the needs of the potential (re)users.
- The question concerns whether there are sufficient attributes (rich metadata) presumably with formal syntax and declared semantics to allow re-use.

**Comment by makxdekkers** [comment]
See also #13

**Comment by keithjeffery** [comment]
To add to the above, the RDA MIG 'element set' (work in progress) aims to provide a base set of elements that should be somehow represented in the metadata, ideally in a common sntax and with comon semantics.  Then extensions can be agreed pairwise for interoprability by communities.  So the concept is the same as Dublin Core (or any other common standard) but with strictly formalised syntax and semantics to allow autonomic interoprability.

**Comment by makxdekkers** [comment]
@keithjeffery Are you saying that the RDA Metadata IG is defining 'yet another' metadata element set with a fixed syntax? How does that relate to, for example, Dublin Core, DCAT, DataCite Kernel?

Is there a draft of that base set of elements available? Could the FAIR Data Maturity Model ask the MIG to come up with proposal for indicators for 'rich metadata'?

**Comment by keithjeffery** [comment]
Makx –
RDA MIG is indeed defining yet another element set (with formal syntax and declared semantics) but it is purposely a superset of all the common metadata formats of general (not domain-specific) applicability and we plan to provide convertors.
The element set is at https://www.rd-alliance.org/groups/metadata-ig.html (scroll down a bit) and alongside each element is the google doc with discussions on it – in some cases discussion is mediated by a leader.

Indeed, it would be good for FDM WG to ask MIG for indicators for rich metadata.
Best
Keith
--------------------------------------------------------------------------------
Keith G Jeffery Consultants
Prof Keith G Jeffery
E: keith.jeffery@keithgjefferyconsultants.co.uk<mailto:keith.jeffery@keithgjefferyconsultants.co.uk>
T: +44 7768 446088
S: keithgjeffery
----------------------------------------------------------------------------------------------------------------------------------
The contents of this email are sent in confidence for the use of the
intended recipient only.  If you are not one of the intended
recipients do not take action on it or show it to anyone else, but
return this email to the sender and delete your copy of it.
----------------------------------------------------------------------------------------------------------------------------------

**Comment by makxdekkers** [comment]
@keithjeffery I'll ask the WG to look at the MIG proposal.

**Comment by micheldumontier** [comment]
indeed, there are many metadata standards and guidelines e.g. http://www.w3.org/TR/hcls-dataset/ , https://www.w3.org/TR/dwbp/, etc etc. we'd like to see these as being encoded in a computatonal language that supports automatic validation.

**Comment by SusannaSansone** [comment]
This discussions links nicely with the content of the RDA FAIRsharing WG registry, which is now one of the formally approved RDA outputs. See also #28 and #29.

Domain/discipline-specific community standards already define the [minimal reporting requirements](https://fairsharing.org/standards/?q=&selected_facets=type_exact:reporting%20guideline), or checklists, outlining the necessary and sufficient information vital for contextualizing and understanding a digital object, especially datasets.

**Comment by makxdekkers** [comment]
@SusannaSansone Would you want to change the wording of the indicator at https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/26#issue-459854499 to something like: "_Use of minimal reporting guidelines for the domain/discipline-specific community standard ..._" or "_Metadata satisfying minimal reporting requirements for the domain/discipline-specific community standard ..._"? Or do you want to propose a different indicator for this principle?

**Comment by RDA-FAIR** [comment]
Please find the current version of the indicator(s) and their respective maturity levels for this FAIR principle. Indicators and maturity levels will be presented, as they stand, to the next working group meeting for approval.  In the meantime, any comments are still welcomed.

The editorial team will now concentrate on weighing and prioritizing these indicators. More information soon.

![image](https://user-images.githubusercontent.com/47179213/62354722-d092e180-b50d-11e9-96c5-511b8a23ea78.png)

**Comment by SusannaSansone** [comment]
@makxdekkers what is the metadata defined by the RDA metadata IG? If you are to point people to some metadata lists, then you should consider also point them to the RDA FAIRsharing WG registry for generic and domain/disciplines standards, since it is an approved/adopted output.

**Comment by makxdekkers** [comment]
@SusannaSansone The Metadata IG lists a set of metadata elements on their RDA page at https://www.rd-alliance.org/groups/metadata-ig.html (scroll down a bit). This was proposed by a member of the WG, and this proposal is open for discussion by the WG. As I proposed in https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/13#issuecomment-518015822, we can refer to FAIRsharing in the indicator R1-01M. Is that OK?

**Comment by SusannaSansone** [comment]
> @SusannaSansone The Metadata IG lists a set of metadata elements on their RDA page at https://www.rd-alliance.org/groups/metadata-ig.html (scroll down a bit). This was proposed by a member of the WG, and this proposal is open for discussion by the WG. As I proposed in [#13 (comment)](https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/13#issuecomment-518015822), we can refer to FAIRsharing in the indicator R1-01M. Is that OK?

@makxdekkers yes, sorry it seems we have repeated our comments in several issues ;-)

**Comment by makxdekkers** [comment]
@SusannaSansone wrote at https://docs.google.com/spreadsheets/d/1mkjElFrTBPBH0QViODexNur0xNGhJqau0zkL4w8RRAw/edit#gid=0

The domain/discipline specific metadata standards (https://fairsharing.org/standards) should be first as these allow the reuse.

**Comment by makxdekkers** [comment]
I suggest to discuss this further at the joint meeting at the 14th RDA plenary, https://www.rd-alliance.org/metadata-fair-data.

**Comment by makxdekkers** [comment]
@JolandaS wrote at https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/30#issuecomment-535419649:
> R1.3-01M: community standards seems to be overlapping with R1-01M. What is the difference with domain/discipline standards?

Reply from @makxdekkers at https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/30#issuecomment-536336554:

> There is indeed overlap between R1 and R1.3. The mention of 'sufficient metadata' in the indicator for R1 is to satisfy the requirement of "plurality and relevance of attributes" in the principle, while the indicators for R1.3 focus on the "standard" aspect. The word 'standard' does not appear in the definition for R1, but was added later based on comments in the meeting on 18 June 2019 (see also [#26 (comment)](https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/26#issuecomment-504982246)) because the richness of metadata is dependent on the community.
> Would it be clearer if the text of the indicators were aligned to mention 'community standard' instead of 'domain/discipline-specific metadata standard' in R1?
