### ISSUE TITLE
When will the FAIRness be assessed? 

### ISSUE THREAD

**Issue by RDA-FAIR** [RDA-FAIR/FAIR-data-maturity-model-WG#3]
Effective data management is carried out for the entire lifecycle of the data, from the point of creation through to dissemination, publication and archiving. In that regard, when the FAIRness of an entity should be assessed (e.g. creation, publication, periodically, etc)?

**Comment by SusannaSansone** [comment]
Ideally at creation, but to be more realistic and practical I would say when data is shared as for made available to others (whatever the mean).

**Comment by kitchenprinzessin3880** [comment]
This depends on the users (& motivation). A data creator may refer to the FAIRness criteria before submitting a dataset to data repository/data journal for publication, or a curator may review the submitted dataset based on FAIRness criteria. Personally i think the FAIRness assessment should be integrated into data centers/providers as they curate, publish and maintain the datasets. Its upto a data center to implement it at data submission or publication stage.

**Comment by rwwh** [comment]
I would start by assessing the _expected_ FAIRness of the resulting data based solely on the information given in a Data Management Plan. The DMP will evolve during the project, and at the end of the project the **predicted** FAIRness will be replaced by an **assessed** FAIRness.

By doing it this way, there is still a possibility to steer a project into a more FAIR direction.

And, in case someone does not know yet, our [Data Stewardship Wizard](https://ds-wizard.org/) actually tries to predict FAIRness and provide the guidance towards more FAIR decisions in the DMP.

**Comment by oyadenizbeyan** [comment]
We have three main patterns to apply FAIR transformation to data: 
1)	Retrospective FAIRification:  This refers to a postmortem analysis of data and transforming it to an improved level of FAIRness. In this case, we can talk about Initial assessment, and final assessment (in between there could be a targeted maturity level) 
2)	Prospective FAIRificiation: This refers to integrating FAIRification into your data generation lifecycle. In this case, as Rob mentioned,  DMP will be the best place to address the FAIRness assessment during the lifecycle. 
3)	Sustainability of FAIR data sets: We also have a problem with ensuring sustainability of FAIRness level over time. Data sets will be assessed and deposited into a repository. However as time pass, there might be problems in referenced metadata, used vocabularies might have updated, we can have broken links, etc. A periodic automated assessment might be needed to detect degradation of FAIRness level.
