### ISSUE TITLE
Indicators prioritisation for Interoperability 

### ISSUE THREAD

**Issue by RDA-FAIR** [RDA-FAIR/FAIR-data-maturity-model-WG#32]
Dear members of the Fair data maturity model Working Group, 

As a next step towards a common set of core assessment criteria, we started to explore the prioritisation of the indicators derived from the contributions to this very repository. As a result, all the indicators have been ranked according to three degrees of priority;

- `Mandatory`: indicator MUST be satisfied for FAIRness
- `Recommended`: indicator SHOULD be satisfied, if at all possible, to increase FAIRness
- `Optional`: Indicator MAY be satisfied, but not necessarily so

In the following [Google spreadsheet](https://docs.google.com/spreadsheets/d/1mkjElFrTBPBH0QViODexNur0xNGhJqau0zkL4w8RRAw/edit#gid=0), you can see the i) indicators in their final version and ii) their priorities. 

![I](https://user-images.githubusercontent.com/47179213/62785365-cb5f0500-bac0-11e9-9655-ac9f474dc87c.png)

Please have a look at the spreadsheet and let us know what are your thoughts, suggestions and concerns with regards to the ranking we attempted to make. 

Thanks in advance for your contribution!

**Comment by gepeng86** [comment]
There is no mandatory indicator for interoperability. I do not see any mandatory indicator for ensuring data to be interoperable, perhaps R1.3-01D but see my comments for R.

**Comment by makxdekkers** [comment]
@gepeng86 Yes, you are right that we didn't propose mandatory indicators for "I". Our thinking was:

- it seems hard to make the ones for I1, concerning knowledge representations, mandatory, because there might be cases that no relevant KR exist for the data at hand

- for I2, data in domains that does not have or recommend standard or FAIR-compliant vocabularies could never be FAIR if the indicators would be mandatory

- it seemed to us that references to other metadata/data can only be included if there are related datasets. If there are not, would data always be unFAIR?

Happy to hear the WG's views on this.

**Comment by keithjeffery** [comment]
Can we finalise the indicator wording for the WG to agree before prioritising - else we risk cycling

**Comment by RDA-FAIR** [comment]
On the 19/08/2019 Mark D Wilkinson commented

In the current proposal, there are no mandatory indicators for interoperability. Should there be?

> Not sure.  They would be pretty general, if there were, because the sub-principles define what was intended.

Read his comment here: https://www.rd-alliance.org/group/fair-data-maturity-model-wg/post/discussion-items-fair-data-maturity-model-19-august-2019

**Comment by makxdekkers** [comment]
@keithjeffery Yes, we want to finalise the wording of the indicators. Do you think the indicators for the I's need to be formulated? What would you propose?

**Comment by makxdekkers** [comment]
@markwilkinson What do you think about the current indicators for the sub-principles I1, I2 and I3 [above](https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/32#issue-479009587)?
Are they sufficiently specific?

**Comment by makxdekkers** [comment]
@keithjeffery @markwilkinson @peterwittenburg Given the discussion at https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/23, we could make all the indicators for I2 optional so that they do not affect the basic FAIRness of a resource under evaluation.

**Comment by keithjeffery** [comment]
I believe some should be mandatory.  Looking at the I3 indicators I seem to miss the obvious one to make mandatory: metadata contains qualified reference to data (or other digital asset). More generally, I think the 'recommended' indicators in the list above could be mandatory

**Comment by makxdekkers** [comment]
@keithjeffery Good point that the proposed indicators only cover metadata->metadata and data->data references and not metadata->data references. We can add two indicators (unqualified/qualified) for those references.

We might want to be careful with making the indicators mandatory. For example, is it always unFAIR not to have any references? Peter Wittenburg argued at https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/25#issuecomment-522307150 that in the case of Big Data there are no references -- making for example the indicator I3-01D mandatory would mean that these Big Data resources could never be FAIR.

@markwilkinson suggested at https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/25#issuecomment-522870877 to add "where possible" which means the indicator would not be mandatory.

**Comment by rwwh** [comment]
@makxdekkers A well placed "where possible" clause makes it possible to make an indicator mandatory, albeit with a certain unsatisfactory level of subjectivity.

**Comment by keithjeffery** [comment]
Even with big data I usually find a qualified link between the metadata and the data

**Comment by nsjuty** [comment]
Metadata should point to the data it is describing, right? If it doesn't, then its just 'data'?

**Comment by makxdekkers** [comment]
@nsjuty The principle I3 is about links from (meta)data to **other** meta(data). The link from the metadata to its own data, i.e. the data it describes, is covered in principle [F3](https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/17).

**Comment by makxdekkers** [comment]
@rwwh

> @makxdekkers A well placed "where possible" clause makes it possible to make an indicator mandatory, albeit with a certain unsatisfactory level of subjectivity.

If a mandatory indicator has a "where possible", it is no longer fully mandatory. An automated FAIR evaluation, when it encounters a failure, would not have a clear means to determine that the failure is because it was not possible to satisfy, or that it has another reason.

In the proposals, _Recommended_ means "... indicator SHOULD be satisfied, if at all possible ..." which could be the way to allow for failure if there is a good reason for non-compliance.

**Comment by rwwh** [comment]
Ok. 

I use this occasion to strengthen an earlier remark I placed elsewhere: if the end goal of this maturity level work is to combine all results into a single binary assessment (data are either FAIR or NOT FAIR) then it is doomed. 

> The FAIR Data principles provide some clear proscriptions and tests for compliance. Issues of inclusion are much more open ended. When have we done enough? What audiences do we need to consider? In that sense it becomes much more a direction of travel than an easily definable goal to reach. But actually that was the initial goal, to prompt and provoke us to think more.  [Cameron Neylon, September 22, 2016](https://cameronneylon.net/blog/fair-enough-fair-for-one-fair-for-all/)

**Comment by makxdekkers** [comment]
@rwwh I was not implying that the result of an evaluation would be a binary, overall assessment. I agree that that is not what people are looking for.
I think of the indicators as a tool to help looking at several aspects of FAIRness in such a way that the evaluation would be able to tell a data provider how a resource being evaluated compares to those specific aspects. So the results of the evaluation of the individual indicators is what the evaluation delivers. Whether or not an evaluator (human or software-based) draws overall conclusions about FAIRness is up to the evaluator.
What the proposed priorisation does try to do, is to provide guidance on how important a particular indicator is. For example, in the case of Findable, the current proposal implies that it is more important to have a UUPID for data (mandatory) than to have a UUPID for the metadata (recommended).
It is open for debate whether this group should try to establish such a prioritisation of indicators in order to establish "core criteria" as a subset of the most important indicators, or that the full list of indicators constitute the "core assessment criteria" that the group is chartered to develop.

**Comment by rwwh** [comment]
@makxdekkers that is a relief. Note that the term "mandatory" for me implies "non-mandatory" for all the other items. We must prevent people from misunderstanding this as "doing everything that is mandatory is enough".

**Comment by makxdekkers** [comment]
@rwwh I see two possible ways of looking at this.

One is that by satisfying all the mandatory indicators, you reach something like a 'minimum FAIRness level'. Satisfying additionally recommended and optional indicators would then reach a higher FAIRness level. This would give an answer to the question "how FAIR is this data?"

A second one would see the mandatory indicators as the ones that contribute the most to FAIRness, possibly as being the ones that have the best effort/benefit ratio, so that a data provider who sees the evaluation mark in several indicators as failed would know where to focus effort to improve. Looking at it this way, this would answer the question "How can the FAIRness of this data be improved?"

Both approaches would aim to get the data under evaluation to satisfy as many indicators as possible, but with the focus of the effort on the most important indicators.

Which one would you prefer, or should we leave it to evaluation approaches to choose how they want to do this?

**Comment by rwwh** [comment]
@makxdekkers I think I slightly prefer the second approach. The first assumes that there is a fixed base FAIRness level that is not dependent on any context.

Note that for me, the word "mandatory" really only works for the first option. If the final recommendation of the group chooses the second, it may be better to replace the "mandatory" priority by "very important" or maybe "essential".

**Comment by makxdekkers** [comment]
@rwwh Yes, finding other words might indeed be helpful if we want to go for the second option. Maybe 'essential', 'important' and 'useful' or something.

I would still want to ask the group for their opinion on which indicators should be mandatory/essential, which should be recommended/important and which optional/useful.

**Comment by hervelh** [comment]
*
“I2. (meta)data use vocabularies that follow FAIR principles”
I won’t be the first person to note that the recursive nature of this principle will need to be addressed. 

*
As others have noted, there are no ‘mandatory’ indicators for interoperable. Given the FAIR work is a driver for so much of EOSC (which will stand or fall on its interoperability) this seems problematic. Making "data and metadata use knowledge representation expressed in a standardised format" as ‘mandatory if applicable’ might help address this i.e. if the “discipline-domain”, “cross-domain” and “community” context has an appropriate standard knowledge expression format. 

*


“I2 I2-01M Metadata uses standard vocabularies Recommended
I2 I2-01D Data uses standard vocabularies Recommended
I2 I2-02M Metadata uses FAIR-compliant vocabularies Optional
I2 I2-02D Data uses FAIR-compliant vocabularies Optional”

It seems hard to justify making FAIR-compliant vocabularies ‘optional’ given that this is an explicit requirement of the principle. Could all of the above be addressed with a ‘mandatory if applicable’ context-dependent approach?

*
In I3-01M to I3-02D all of the references are data-data or metadata-metadata. What is the argument for excluding references between data and metadata? 

*
Could the related metadata and data indicators be placed next to each other in sequence? This is done under F and makes it easier to compare/contrast.

**Comment by makxdekkers** [comment]
@hervelh 

> “I2. (meta)data use vocabularies that follow FAIR principles”
> I won’t be the first person to note that the recursive nature of this principle will need to be addressed.

There is a discussion about this at https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/24.

**Comment by makxdekkers** [comment]
@hervelh 

> As others have noted, there are no ‘mandatory’ indicators for interoperable. Given the FAIR work is a driver for so much of EOSC (which will stand or fall on its interoperability) this seems problematic. Making "data and metadata use knowledge representation expressed in a standardised format" as ‘mandatory if applicable’ might help address this i.e. if the “discipline-domain”, “cross-domain” and “community” context has an appropriate standard knowledge expression format.

This is what we can decide 'recommended' means. As [RFC2119](https://www.ietf.org/rfc/rfc2119.txt) says: "_there may exist valid reasons in particular circumstances to ignore a particular item, but the full implications must be understood and carefully weighed before choosing a different course_"

**Comment by makxdekkers** [comment]
@hervelh 

> It seems hard to justify making FAIR-compliant vocabularies ‘optional’ given that this is an explicit requirement of the principle. Could all of the above be addressed with a ‘mandatory if applicable’ context-dependent approach?

The problem with this indicator is that it has been acknowledged above that there are not many FAIR-compliant vocabularies, making it very hard or even impossible to satisfy this indicator.

**Comment by makxdekkers** [comment]
@hervelh 

> In I3-01M to I3-02D all of the references are data-data or metadata-metadata. What is the argument for excluding references between data and metadata?

We'll add references from metadata to 'other' data as proposed in https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/32#issuecomment-525246486.

**Comment by makxdekkers** [comment]
@hervelh 

> Could the related metadata and data indicators be placed next to each other in sequence? This is done under F and makes it easier to compare/contrast.

We'll make this consistent.

**Comment by hervelh** [comment]
> @hervelh
 As others have noted, there are no ‘mandatory’ indicators for interoperable. Given the FAIR work is a driver for so much of EOSC (which will stand or fall on its interoperability) this seems problematic. Making "data and metadata use knowledge representation expressed in a standardised format" as ‘mandatory if applicable’ might help address this i.e. if the “discipline-domain”, “cross-domain” and “community” context has an appropriate standard knowledge expression format.
> 
> This is what we can decide 'recommended' means. As [RFC2119](https://www.ietf.org/rfc/rfc2119.txt) says: "_there may exist valid reasons in particular circumstances to ignore a particular item, but the full implications must be understood and carefully weighed before choosing a different course_"

@makxdekkers OK, this aligns with RFC2119. Does this imply that any test against a Recommended indicator needs a second stage in the case of a 'fail'? i,e, an opportunity to justify the failure?

**Comment by hervelh** [comment]
> @hervelh
> 
> > It seems hard to justify making FAIR-compliant vocabularies ‘optional’ given that this is an explicit requirement of the principle. Could all of the above be addressed with a ‘mandatory if applicable’ context-dependent approach?
> 
> The problem with this indicator is that it has been acknowledged above that there are not many FAIR-compliant vocabularies, making it very hard or even impossible to satisfy this indicator.

@makxdekkers So this could be ‘Recommended’ with the justification for not meeting the recommendation to use FAIR-Compliant Vocabularies being “there aren’t any”?

**Comment by makxdekkers** [comment]
@hervelh 
> @makxdekkers OK, this aligns with RFC2119. Does this imply that any test against a Recommended indicator needs a second stage in the case of a 'fail'? i,e, an opportunity to justify the failure?

At this point, we do not go into the details of evaluation. We're trying to define **what** to evaluate, not **how** the evaluation is done. The general idea of Recommended is that a data provider should satisfy the indicator unless there is a good reason not to. That could indeed mean a two-stage process.

**Comment by makxdekkers** [comment]
@hervelh 
> @makxdekkers So this could be ‘Recommended’ with the justification for not meeting the recommendation to use FAIR-Compliant Vocabularies being “there aren’t any”?

Yes, that would be a good reason not to satisfy the indicator.

**Comment by makxdekkers** [comment]
@helenp Apologies, I overlooked your comment. 
Your suggestion to change principle 2 is outside of the scope of this Working Group: we take the current FAIR principles as our fixed basis. People involved in the formulation of the FAIR principles might want to take your comment into account if and when they decide to review and revise the principles. @markwilkinson?

**Comment by gepeng86** [comment]
Going through all the indicators in one pass for the prioritization allows me to see more on their overall consistency which leads to my issues below. My apology if it has been brought up to the WG previously as I have not kept up with the discussions due to travel/leave and catching up from the travel/leave.

I1-01M;01D;02M;02D;03M:  Metadata is information about data. Knowledge is gained from analyzing the data with information contained in data and associated metadata. I am not sure using “knowledge” in those indicators is correct or appropriate. Perhaps I misunderstood what “knowledge” means in this context.

**Comment by keithjeffery** [comment]
@gepeng86 I think 'knowledge' was being used in the sense of knowledge representtion ie. triples (e.g. RDF) or n-tuples with logic assertions

**Comment by makxdekkers** [comment]
@gepeng86 The phrase "knowledge representation" used in those indicators comes from the principle itself: "I1: (Meta)data use a formal, accessible, shared, and broadly applicable language for **knowledge representation**" (see https://www.go-fair.org/fair-principles/i1-metadata-use-formal-accessible-shared-broadly-applicable-language-knowledge-representation/).

**Comment by gepeng86** [comment]
Interesting … Thanks a lot, @ makxdekkers, for pointing it out and providing the link.

**Comment by kitchenprinzessin3880** [comment]
@makxdekkers 
apologies for raising again the questions below. i cannot find their answers/explanations in this issue, and also in [previous issue](https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/23) .

- I1-01M | Metadata uses knowledge representation expressed in standardised format (mandatory)
--> here, do you focus on the assessment of the format (rdf,xml,owl) used by the vocabulary, or the content, or both?
--> what is 'standardized format', and how can we determine the formats?

- I1-02M | Metadata uses machine-understandable knowledge representation (mandatory)
- I1-03M | Metadata uses self-describing knowledge representation (optional)
What is the difference between machine-understandable and self-describing?

I2-01M | Metadata uses standard vocabularies (recommended)
--> the term 'use' here should be clarified. there are various ways through which metadata may use semantic vocabularies, and the ways depend on the purpose of their applications (e.g., to support data search, cataloging, data integration, etc.). for example, we can embed semantic vocabularies in the metadata (e.g., annotation), or publish the entire metadata in semantic format (e.g., rdf).
--> in my opinion, if this indicator is recommended, then I1-01M cannot be mandatory.

**Comment by bahimc** [comment]
Dear contributors, 

As reminded during our [fifth workshop](https://www.rd-alliance.org/system/files/documents/20191023_FAIR_WG_Workshop_5_v0.02.pdf) in Helsinki, the **[current state of the indicators](https://docs.google.com/spreadsheets/d/1mkjElFrTBPBH0QViODexNur0xNGhJqau0zkL4w8RRAw/edit#gid=1558529297)** - and their priorities, as of early October 2019, is now frozen. The current indicators will be used in a testing phase where owners of evaluation approaches are invited to compare their approaches (questionnaires, tools) against the indicators. More information concerning the testing phase will be communicated during [workshop #6](https://www.rd-alliance.org/group/fair-data-maturity-model-wg/post/rda-fair-data-maturity-model-workshop-6-preparation), on the 4th of December. 

As such, the current set of indicators can be seen as an ‘alpha version’. In the first half of 2020, the indicators may be revised and improved, based on the results of the testing. 

Should you have any question or feedback, please reply to this comment.

**Comment by makxdekkers** [comment]
@kitchenprinzessin3880 
My take on those issues:

> * I1-01M | Metadata uses knowledge representation expressed in standardised format (mandatory)
>   --> here, do you focus on the assessment of the format (rdf,xml,owl) used by the vocabulary, or the content, or both?
>   --> what is 'standardized format', and how can we determine the formats?

This indicator is formulated as a shorter version of the principle "_I1: (Meta)data use a formal, accessible, shared, and broadly applicable language for knowledge representation_". 
The examples at GO-FAIR (https://www.go-fair.org/fair-principles/i1-metadata-use-formal-accessible-shared-broadly-applicable-language-knowledge-representation/) show some of the standards that would qualify under this principle.

> * I1-02M | Metadata uses machine-understandable knowledge representation (mandatory)
> * I1-03M | Metadata uses self-describing knowledge representation (optional)
>   What is the difference between machine-understandable and self-describing?
> 
> I2-01M | Metadata uses standard vocabularies (recommended)
> --> the term 'use' here should be clarified. there are various ways through which metadata may use semantic vocabularies, and the ways depend on the purpose of their applications (e.g., to support data search, cataloging, data integration, etc.). for example, we can embed semantic vocabularies in the metadata (e.g., annotation), or publish the entire metadata in semantic format (e.g., rdf).

The word 'use' here indicates that the values (or objects in RDF-speak) of the metadata should be taken from controlled lists. It does not say anything about how to use those values. Maybe we need to add the word controlled, e.g. 'standard controlled vocabularies', which would align better with the explanatory text from GO-FAIR at https://www.go-fair.org/fair-principles/i2-metadata-use-vocabularies-follow-fair-principles/?

> --> in my opinion, if this indicator is recommended, then I1-01M cannot be mandatory.

The priorities (mandatory/recommended/optional) of the indicators were taken from the outcome of the survey. They can be changed based on the experience in the testing. If there is a contradiction there, it is likely to come out of the testing.

It would be good to get other opinions on the issues you raise. All those comments will be taken into account in the further development of the indicators in the next months.
