### ISSUE TITLE
Indicators prioritisation for Reusability 

### ISSUE THREAD

**Issue by RDA-FAIR** [RDA-FAIR/FAIR-data-maturity-model-WG#33]
Dear members of the Fair data maturity model Working Group, 

As a next step towards a common set of core assessment criteria, we started to explore the prioritisation of the indicators derived from the contributions to this very repository. As a result, all the indicators have been ranked according to three degrees of priority;

- `Mandatory`: indicator MUST be satisfied for FAIRness
- `Recommended`: indicator SHOULD be satisfied, if at all possible, to increase FAIRness
- `Optional`: Indicator MAY be satisfied, but not necessarily so

In the following [Google spreadsheet](https://docs.google.com/spreadsheets/d/1mkjElFrTBPBH0QViODexNur0xNGhJqau0zkL4w8RRAw/edit#gid=0), you can see the i) indicators in their final version and ii) their priorities. 

![R](https://user-images.githubusercontent.com/47179213/62785401-dd40a800-bac0-11e9-9eab-acbc0ce1b5a9.png)

Please have a look at the spreadsheet and let us know what are your thoughts, suggestions and concerns with regards to the ranking we attempted to make. 

Thanks in advance for your contribution!

**Comment by gepeng86** [comment]
The mandatory indicator R1.3-01D is ambiguous. There are well-established community metadata standards. Are there any well-established community data standards? What community standards does it refer to for data to be compliant with: file naming conventions, file formats, file structures, standard variable names, …? Implementation of this indicator may be extremely arbitrary.

**Comment by makxdekkers** [comment]
@gepeng86 I don't know whether there are written or unwritten rules for data formats and other data-related characteristics. I can imagine that disciplines do have some commonality, for example that data is published in Excel or CSV or SDMX. I found this https://guides.library.ucla.edu/c.php?g=180580&p=1186565 as a list of recommendations for the humanities which could be part of the evaluation of the indicator for that domain.
However, if a community doesn't have a standard for data, it would be hard for data in that domain to be FAIR.
Should the indicator be "Recommended" instead?

**Comment by barbaragit2019** [comment]
Barbara Sierman: I miss requirements related to the technical environment that is needed to re-use the data: file format of the data, software needed etc. As the R in FAIR is a starting point for preservation, this is crucial information to make preservation succesfull.

**Comment by makxdekkers** [comment]
@barbaragit2019 I think this should be covered under principle R1 as part of the "sufficient metadata ... to allow reuse". 

We are discussing what "rich metadata" means at https://github.com/RDA-FAIR/FAIR-data-maturity-model-WG/issues/13, but so far we haven't been able to pin down what this means, other than recommending compliance with community-specific guidelines.

Would you suggest to add a specific indicator for the inclusion of information about the technical environment in the metadata?

**Comment by gepeng86** [comment]
Thanks, @makxdekkers, for your quick response.

I am okay with this indicator being mandatory. I am just wondering if we should somehow narrow the scope of it to reduce possible misinterpretation when determining what to evaluate and how to evaluate it.

Are you suggesting the community standard refers to that for file format? Yes, there are community accepted file formats. Then it should perhaps be stated such. The current verbiage for this indicator seems to imply more than just file format.  

For example, given the example you provided, the same website also lists the standards for data description. It has in fact indicated that data format is a “particular convention for data representation”.

So, are we talking about “Data format complies with a community standard” or “Data representation complies with a community standard” or “Data description complies with a community standard”? That’s why I think “Data complies with a community standard” is too vague.

I am definitely open to other perspectives. If the scope of this indicator should be narrowed, it would be good to get a WG’s consensus. 

Regards,

--- Peng

**Comment by RDA-FAIR** [comment]
On the 19/08/2019, Mark D Wilkinson commented 

Should there be a separate indicator concerning the provision of information in the metadata about the technical environment needed to re-use data?

> The word "plurality" was the only word that we (Michel, actually, decided on that word, and others at the table agreed with it) could find that described the concept of "giving as much metadata as you possibly could, without presuming who the end user might be, and then giving some more!".  So yes, technical environment would definitely be a part of that.

The indicator “_Data complies with a community standard_” is too vague. Could it be narrowed to “_Data format complies with a community standard_” or “_Data representation complies with a community standard_” or “_Data description complies with a community standard_”?

> I think it really meant:  if there IS a standard, then be sure you use it.  If there ISN'T a standard, you should consider if the problem can be standardized, and then create one.   -->  The more predictable structure, the better!  And only the community can decide what metadata elements are really important for reproducibility and reuse of their data.

Read his comments here: https://www.rd-alliance.org/group/fair-data-maturity-model-wg/post/discussion-items-fair-data-maturity-model-19-august-2019

**Comment by hervelh** [comment]
“R1 R1-01M Sufficient metadata is provided to allow reuse, following domain/discipline-specific metadata standard Recommended”

Given that re-usability is a top tier principle, shouldn’t this be mandatory? The “domain/discipline” context should be enough to identify appropriate assessment criteria for this. 

*
Given that accuracy is explicit in R1 is seems there should be an indicator which addresses quality? At least in terms of complete, timely, valid, consistent etc

*

“R1.1 R1.1-06M Metadata includes information about consent for reuse (e.g. for personal data) Recommended”

Is this included because personal data is such an important data type? No other data characteristics are referenced explicitly in the indicators. I wonder whether it is redundant here? If  “R1.1-01M Metadata includes information about the licence under which the data can be reused” is applied correctly then consent, or other data use permissions (commercially sensitive, IPR encumbered etc) will all be addressed. 
*
Is the use of “cross-domain” here for a specific reason (as opposed to community or discipline/domain used elsewhere)?

**Comment by makxdekkers** [comment]
@hervelh 

> “R1 R1-01M Sufficient metadata is provided to allow reuse, following domain/discipline-specific metadata standard Recommended”
> 
> Given that re-usability is a top tier principle, shouldn’t this be mandatory? The “domain/discipline” context should be enough to identify appropriate assessment criteria for this.

The indicator is 'recommended' to allow for cases where there is no metadata standard to follow.

**Comment by makxdekkers** [comment]
@hervelh 

> Given that accuracy is explicit in R1 is seems there should be an indicator which addresses quality? At least in terms of complete, timely, valid, consistent etc

Would that not be the role of the metadata standard to be followed?

The issue of quality may be a more horizontal issue, i.e. in all the indicators you would expect any information to be correct, up-to-date, valid etc.

**Comment by makxdekkers** [comment]
@hervelh 

> “R1.1 R1.1-06M Metadata includes information about consent for reuse (e.g. for personal data) Recommended”
> 
> Is this included because personal data is such an important data type? No other data characteristics are referenced explicitly in the indicators. I wonder whether it is redundant here?

This indicator was explicitly added by a member of Working Group in one of the early stages of the work.
The question to the Working Group is whether the indicator should be deleted?

**Comment by keithjeffery** [comment]
In an ideal world R1.1-06M could/should be subsumed under R1.-01M; however not all licencing schemes deal specifically with reuse of sensitive data such as personal data and the GDPR makes this aspct of reuse particularly sensitive.
For this reason I would be in favour of retaining R1.1-06M

**Comment by andrasholl** [comment]
I agree that R1.3-01 "community standard" is too vague. Priority should be reduced to "recommended". But another requirement could be added: a reference to the community standard being used. (It could be a DOI which points to a relevant document.)

**Comment by makxdekkers** [comment]
@andrasholl Your proposal to make R1.3-01 (assuming you mean both the indicators for metadata and data) is noted. This proposal is open for comment by the other members of the WG.
Your suggestion that a reference to the standard is included should probably be taken up in the discussion about '_rich metadata_' in F2 and the '_plurality of attributes_' in R1 that will take place at  the [Metadata for FAIR Data meeting at the 14th RDA plenary](https://www.rd-alliance.org/metadata-fair-data).

**Comment by hervelh** [comment]
> @hervelh
> 
> > “R1 R1-01M Sufficient metadata is provided to allow reuse, following domain/discipline-specific metadata standard Recommended”
> > Given that re-usability is a top tier principle, shouldn’t this be mandatory? The “domain/discipline” context should be enough to identify appropriate assessment criteria for this.
> 
> The indicator is 'recommended' to allow for cases where there is no metadata standard to follow.

@makxdekkers
Sorry that this RFC query is spread over different issues!
OK, this is in line with the strict application of RFC2119 (a good thing). So the underlying philosophy (to avoid the term ‘principle’) is that for global FAIR indicators the status *must* be Recommended for any principle which has a second-tier dependency on context (community standard, domain-disciplinary protocol etc)? Because that second tier context may not be available?

**Comment by hervelh** [comment]
> @hervelh
> 
> > Given that accuracy is explicit in R1 is seems there should be an indicator which addresses quality? At least in terms of complete, timely, valid, consistent etc
> 
> Would that not be the role of the metadata standard to be followed?
> 
> The issue of quality may be a more horizontal issue, i.e. in all the indicators you would expect any information to be correct, up-to-date, valid etc.

@makxdekkers
OK, not sure I’ve grokked your point.  My initial thoughts on this are that tests (or at least automated tests) to validate the R1 indicators in terms of *accuracy* depend on I1 (Formal knowledge representation) but *relevance*  has a dependency on R4 (domain-relevant community standards)?

**Comment by hervelh** [comment]
@makxdekkers @keithjeffery
I completely understand the motivation for R1.1-06M and my gut feeling (possibly because my place works extensively with personal and de-identified data) is that this belongs in the top tier of indicators. But one issue is that consent isn’t the only contextual variable (cf: GDPR derogations for research and archiving) and another is that the failures of some licencing schemes shouldn’t drive indicator definitions at this (important) core level. I agree that there is a broad reliance on prose licence approaches, but I think the need for machine-actionable rights models (ODRL etc) is a separate discussion. So with my information modelling head on, I think I’d need to go ahead and propose that this indicator is deleted. I think that addressing 'consent' would best fit in context-dependant testing i.e. with one relevant contextual variable being “is/is not personal data”.

**Comment by hervelh** [comment]
@andrashol
Agree with the proposal to move to *recommended* if we strictly apply the terminology in RFC2119. But disagree on the term “vague” (even though it is:). I suggest that several indicators depend on context, in this case, a definition of community standards and an understanding of what constitutes community support/adoption are both required. If we’re looking to define indicators and then tests (as opposed to listing requirements) I guess that a reference to a community standard is a dependency for testing. 

@makxdekkers
I agree that context-dependent scenarios like community standard, rich metadata (F2) and plurality of attributes (R1) need a common philosophy of approach. It’s doubtful I can join the call on the 12th, but I hope to join the RDA Plenary meeting.

**Comment by keithjeffery** [comment]
We should not get hung up on de jure standards.  There are many de facto standards used in various domain communities, some are modified versions of de jure standards.  Furthermore, new 'standards' are emerging all the time and if they increase FAIR why not use them?  De jure standards take a long time to be formalised and at that time the technical optimal solutions are usually beyond the de jure standard.  The underlying quesion is use of metadata for reusability over what scope - within restricted scientific domain or universally?

**Comment by andrasholl** [comment]
I agree that a somewhat more relaxed approach is needed, we would hold up research if we would require very formal
standards. My point is that we should require a reference to some publicly available data domain protocol,
or document, which can claim some degree of community agreement. Requiring conformance to community
standards without specifying what it is, without referring to any kind of public description of the given standard is vague, it is an empty
requirement.

Andras Holl 
----- Original Message -----

**Comment by makxdekkers** [comment]
@andrasholl You are right of course that it would be necessary to have more information about what the standard is and how a resource under evaluation conforms to it.
However, the indicators aim at determining **what** should be evaluated, not **how** they should be evaluated. In evaluating a particular resource, it would be necessary to look at the details of what the resource claims to conform to, and this could be through looking up the relevant standard in the FAIRsharing registry or some other tool. It would then be up to the evaluator to decide whether the conformance to an appropriate standard is good enough or not, always with the perspective in mind that it needs to facilitate reuse.

**Comment by andrasholl** [comment]
I absolutely agree.

Andras Holl

----- Original Message -----

**Comment by bahimc** [comment]
Dear contributors, 

As reminded during our [fifth workshop](https://www.rd-alliance.org/system/files/documents/20191023_FAIR_WG_Workshop_5_v0.02.pdf) in Helsinki, the **[current state of the indicators](https://docs.google.com/spreadsheets/d/1mkjElFrTBPBH0QViODexNur0xNGhJqau0zkL4w8RRAw/edit#gid=1558529297)** - and their priorities, as of early October 2019, is now frozen. The current indicators will be used in a testing phase where owners of evaluation approaches are invited to compare their approaches (questionnaires, tools) against the indicators. More information concerning the testing phase will be communicated during [workshop #6](https://www.rd-alliance.org/group/fair-data-maturity-model-wg/post/rda-fair-data-maturity-model-workshop-6-preparation), on the 4th of December. 

As such, the current set of indicators can be seen as an ‘alpha version’. In the first half of 2020, the indicators may be revised and improved, based on the results of the testing. 

Should you have any question or feedback, please reply to this comment.
