### ISSUE TITLE
FAIR indicator v0.03

### ISSUE THREAD

**Issue by FuqiX** [RDA-FAIR/FAIR-data-maturity-model-WG#37]
Could you please update the FAIR indicators v0,03 to this repo? 
We are using the RDA v0,03. It would be great if we have a semi-permanent link to point to the indicators.

**Comment by bahimc** [comment]
Hi @FuqiX, thanks for your comment. 
You can find the [link](https://docs.google.com/spreadsheets/d/1mkjElFrTBPBH0QViODexNur0xNGhJqau0zkL4w8RRAw/edit#gid=1558529297) which points to the indicators. 
Please note that each sheet corresponds to one version of the indicators. As of today, we are in v0.04.

**Comment by FuqiX** [comment]
Hi, thank you for the reply. It's great to see it actively updating!
