### ISSUE TITLE
What would be the format of the assessment?

### ISSUE THREAD

**Issue by RDA-FAIR** [RDA-FAIR/FAIR-data-maturity-model-WG#9]
Will the assessment be automated or manual or even a combination of both?

**Comment by JPetters2931** [comment]
The approach we took in the Data Fitness for Use WG is to first determine what aspects are important to assess, whether they are automatable or not. And then we automate what we can!

I would argue that a world where we can automate assessment of all FAIR metrics (especially for evaluating the reusability of data within a domain) is a world that does not exist yet. An important question is how long we are away from such a world...

**Comment by RDA-FAIR** [comment]
**This issue has been resolved**. You can find further information about it in the _Presentation_ (slide 10) and _Report_ (page 6) of the second workshop https://www.rd-alliance.org/workshop-2
